name: Version Bump
on:
  workflow_dispatch:
jobs:
  publish-packages:
    runs-on: ubuntu-22.04
    # permissions:
    #   contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Update version bump
        run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run version-bump -- --yes
